// importing functions that interact with database form Storage folde
const { insertingReservation, deletingReservation, patchingReservation } = require('../Storage/reservationStorage.js');
// importing library for id generator
const { v4 } = require('uuid');

class Reservation{
    constructor(clientID, date, hotelName, price, balance, reservationID = v4()){
        // declaring all attributes - if reservationID not given in input, it will be generated by library
        this.reservationID = reservationID;
        this.clientID = clientID;
        this.date = date;
        this.hotelName = hotelName;
        this.price = price;
        this.balance = balance;
    }

    calculateBalance(){
        // method for calculating the balance
        this.balance += this.price;
    }

    insertReservation(){
        // method for inserting a reservation in the database
        insertingReservation(this.reservationID, this.clientID, this.date, this.hotelName, this.price, this.balance);
    }

    deleteReservation(){
        // method for deleting a reservation in database
        deletingReservation(this.reservationID);
    }

    patchReservation(){
        // method for patching a reservation in database
        patchingReservation(this.reservationID, this.clientID, this.date, this.hotelName, this.price, this.balance);
    }
};

module.exports.Reservation = Reservation;